item {
    id: 1
    name: 'photo'
}

item {
    id: 2
    name: 'pillow'
}

item {
    id: 3
    name: 'tv'
}

item {
    id: 4
    name: 'plant'
}

item {
    id: 5
    name: 'sofa'
}

item {
    id: 6
    name: 'lamp'
}

item {
    id: 7
    name: 'table'
}

item {
    id: 8
    name: 'painting'
}

item {
    id: 9
    name: 'book'
}

item {
    id: 10
    name: 'glass'
}

item {
    id: 11
    name: 'chair'
}

item {
    id: 12
    name: 'clock'
}